const { DataTypes } = require('sequelize');
const BaseModel = require('../../../main/utils/DB/baseModel');

module.exports = (sequelize) => sequelize.define(
  'Policy',
  {
    ...BaseModel.attributes,
    parent_id: { type: DataTypes.INTEGER, allowNull: true },
    external_id: { type: DataTypes.STRING(255), allowNull: true },
    esbd_id: { type: DataTypes.INTEGER, allowNull: true },
    global_id: { type: DataTypes.STRING(255), allowNull: true },
    policy_number: { type: DataTypes.STRING(255), allowNull: true },
    premium: { type: DataTypes.INTEGER, allowNull: true },
    calculated_premium: { type: DataTypes.INTEGER, allowNull: true },
    discount: { type: DataTypes.INTEGER, allowNull: true },
    period: { type: DataTypes.STRING(255), allowNull: true },
    date_beg: { type: DataTypes.DATEONLY, allowNull: true },
    date_end: { type: DataTypes.DATEONLY, allowNull: true },
    policy_date: { type: DataTypes.DATE, allowNull: true },
    created_here: { type: DataTypes.INTEGER, allowNull: true },
    creator_id: { type: DataTypes.INTEGER, allowNull: true },
    creator_id_1c: { type: DataTypes.INTEGER, allowNull: true },
    manager_id_1c: { type: DataTypes.INTEGER, allowNull: true },
    agent_id_1c: { type: DataTypes.INTEGER, allowNull: true },
    agent_specified: { type: DataTypes.INTEGER, allowNull: true },
    subagent_id_1c: { type: DataTypes.INTEGER, allowNull: true },
    branch_id: { type: DataTypes.INTEGER, allowNull: true },
    sales_channel_id_1c: { type: DataTypes.INTEGER, allowNull: true },
    detailing_id_1c: { type: DataTypes.INTEGER, allowNull: true },
    sent_to_ones: { type: DataTypes.INTEGER, allowNull: true },
    attempts_count: { type: DataTypes.INTEGER, allowNull: true },
    status: { type: DataTypes.INTEGER, allowNull: true },
    target_status: { type: DataTypes.INTEGER, allowNull: true },
    esbd_response: { type: DataTypes.TEXT, allowNull: true },
    esbd_body: { type: DataTypes.TEXT, allowNull: true },
    ones_response: { type: DataTypes.TEXT, allowNull: true },
    ones_body: { type: DataTypes.TEXT, allowNull: true },
    verify_bool: { type: DataTypes.INTEGER, allowNull: true },
    online_bool: { type: DataTypes.INTEGER, allowNull: true },
    holds: { type: DataTypes.INTEGER, allowNull: true },
    affiliated: { type: DataTypes.INTEGER, allowNull: true },
    middleman_id: { type: DataTypes.INTEGER, allowNull: true },
    middleman_contract_number: { type: DataTypes.STRING(255), allowNull: true },
    is_replacement: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    refund_amount: { type: DataTypes.INTEGER, allowNull: true },
    termination_reason: { type: DataTypes.INTEGER, allowNull: true },
    terminator_id_1c: { type: DataTypes.INTEGER, allowNull: true },
    terminated_at: { type: DataTypes.DATE, allowNull: true },
    refund_method: { type: DataTypes.INTEGER, allowNull: true },
    bank_name: { type: DataTypes.STRING(255), allowNull: true },
    iban: { type: DataTypes.STRING(255), allowNull: true },
    bin: { type: DataTypes.STRING(255), allowNull: true },
    bik: { type: DataTypes.STRING(255), allowNull: true },
    mutual_contract_number: { type: DataTypes.STRING(255), allowNull: true },
    mutual_refund_amount: { type: DataTypes.INTEGER, allowNull: true },
    allowed: { type: DataTypes.TINYINT(1), allowNull: true },
  },
  BaseModel.getOptions({ tableName: 'policies', withSoftDelete: false }),
);
